import { useEffect, useRef } from 'react';
import { useTelemetryStream } from './useTelemetryStream.js';
import { usePestForecast } from './usePestForecast.js';
import { useAlertQueue, ALERT_SOURCE } from '../contexts/AlertQueueContext.jsx';
import { classifyEmergenceRisk } from '../utils/mathModels.js';

/**
 * Geo-Farm — Auto-Alert Monitor
 * SIH26131: Early detection & management of crop diseases and pest infestations
 *
 * This is the piece that actually makes the system an "early warning"
 * system rather than a passive dashboard: it watches the live telemetry
 * and pest-forecast streams in real time and automatically raises an
 * officer-review alert the moment a node/trap crosses into HIGH risk or
 * above — without waiting for a human to run a manual leaf scan.
 *
 * Design notes (why this doesn't spam the queue):
 *   - Edge-triggered: an alert only fires when risk RISES into a new,
 *     higher severity band than the last one alerted for that node/trap
 *     (a rising-edge detector), not on every tick while it stays elevated.
 *   - Auto-resets: once risk falls back below MODERATE, that node/trap's
 *     alert state clears, so a future re-escalation fires a fresh alert.
 *   - Cooldown floor: if risk stays pinned at SEVERE/CRITICAL for a long
 *     time (a genuinely ongoing outbreak), it re-alerts at most once per
 *     45 seconds rather than never again — officers shouldn't lose track
 *     of a sustained critical event.
 *
 * Mount this once near the root of the app (inside the providers) via
 * `useAutoAlertMonitor()` — it renders nothing, it's a pure side-effect hook.
 */

const RISK_RANK = { LOW: 0, MODERATE: 1, HIGH: 2, SEVERE: 3, CRITICAL: 4 };
const ALERT_FLOOR_RANK = RISK_RANK.HIGH; // only auto-alert at HIGH severity or above
const RESET_FLOOR_RANK = RISK_RANK.MODERATE; // below this, clear alert memory
const RE_ALERT_COOLDOWN_MS = 45_000;

// BUGFIX (B6): emergence-risk banding now imported from mathModels.js
// (classifyEmergenceRisk) instead of being duplicated here — this used to
// be a second, independently-maintained copy of the exact same thresholds
// used in PestForecastPanel.jsx, risking silent drift between what an
// officer sees on screen and what actually triggers an alert.

function shouldFire(rank, state, now) {
  const isRisingEdge = rank >= ALERT_FLOOR_RANK && rank > state.lastAlertedRank;
  const isSustainedCritical =
    rank >= RISK_RANK.SEVERE &&
    rank === state.lastAlertedRank &&
    now - state.lastAlertTime > RE_ALERT_COOLDOWN_MS;
  return isRisingEdge || isSustainedCritical;
}

export function useAutoAlertMonitor() {
  const { readingsByNode } = useTelemetryStream('*');
  const { readingsByTrap } = usePestForecast('*');
  const { addAlert } = useAlertQueue();

  const telemetryState = useRef({}); // nodeId -> { lastAlertedRank, lastAlertTime }
  const pestState = useRef({}); // trapId -> { lastAlertedRank, lastAlertTime }

  // --- Telemetry (fungal infection risk) watcher ---
  useEffect(() => {
    Object.values(readingsByNode).forEach((reading) => {
      if (!reading) return;
      const level = reading.risk.dominantRiskLevel;
      const rank = RISK_RANK[level] ?? 0;
      const now = Date.now();
      const state = telemetryState.current[reading.nodeId] ?? { lastAlertedRank: -1, lastAlertTime: 0 };

      if (shouldFire(rank, state, now)) {
        addAlert({
          source: ALERT_SOURCE.TELEMETRY,
          riskLevel: level,
          title: `${reading.risk.dominantPathogen} risk escalation — ${reading.label}`,
          description: `Auto-detected by shared-node sensor network: ${reading.smoothedTemp}°C, ${reading.humidity}% RH, ${reading.lwdHours}h continuous leaf wetness. Infection risk score ${(reading.risk.dominantRiskScore * 100).toFixed(0)}%.`,
          confidence: reading.risk.dominantRiskScore,
          metadata: { nodeId: reading.nodeId, crop: reading.crop, autoGenerated: true },
        });
        telemetryState.current[reading.nodeId] = { lastAlertedRank: rank, lastAlertTime: now };
      } else if (rank < RESET_FLOOR_RANK && state.lastAlertedRank !== -1) {
        telemetryState.current[reading.nodeId] = { lastAlertedRank: -1, lastAlertTime: state.lastAlertTime };
      }
    });
  }, [readingsByNode, addAlert]);

  // --- Pest forecast (swarm emergence risk) watcher ---
  useEffect(() => {
    Object.values(readingsByTrap).forEach((trap) => {
      if (!trap) return;
      const level = classifyEmergenceRisk(trap.degreeDay.percentToEmergence);
      const rank = RISK_RANK[level] ?? 0;
      const now = Date.now();
      const state = pestState.current[trap.trapId] ?? { lastAlertedRank: -1, lastAlertTime: 0 };

      if (shouldFire(rank, state, now)) {
        addAlert({
          source: ALERT_SOURCE.PEST_FORECAST,
          riskLevel: level,
          title: `${trap.pestLabel} swarm forecast — ${trap.label}`,
          description: `Auto-detected by pheromone trap network: ${trap.nightlyCatch} catch/night (7-night avg ${trap.avgCatch7Night}, threshold ${trap.economicThreshold}), ${trap.degreeDay.percentToEmergence}% of degree-day emergence threshold reached.`,
          confidence: trap.degreeDay.percentToEmergence / 100,
          metadata: { trapId: trap.trapId, pest: trap.pest, autoGenerated: true },
        });
        pestState.current[trap.trapId] = { lastAlertedRank: rank, lastAlertTime: now };
      } else if (rank < RESET_FLOOR_RANK && state.lastAlertedRank !== -1) {
        pestState.current[trap.trapId] = { lastAlertedRank: -1, lastAlertTime: state.lastAlertTime };
      }
    });
  }, [readingsByTrap, addAlert]);
}

export default useAutoAlertMonitor;
